### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [moritzgubler/vc-sqnm#4]
I suggest adding topics such as `numerical-optimization`, `quasi-newton` in the About section at https://github.com/moritzgubler/vc-sqnm

**Comment by moritzgubler** [comment]
Hi @Beliavsky 
Thanks for the suggestion. I just took a look at your profile and have seen, that you opened similar issues in around 30 different repositories.
May I ask what you are trying to achieve here?

**Comment by Beliavsky** [comment]
To make projects, especially Fortran projects, more easily discoverable through topic searches.

**Comment by moritzgubler** [comment]
Perfect, thanks
